apiVersion: v1
kind: Namespace
metadata:
  name: flipsync-prod
  labels:
    name: flipsync-prod
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: flipsync-staging
  labels:
    name: flipsync-staging
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: flipsync-dev
  labels:
    name: flipsync-dev
    environment: development
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: flipsync-quota
  namespace: flipsync-prod
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "50"
    services: "20"
    persistentvolumeclaims: "20"
    secrets: "100"
    configmaps: "100"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: flipsync-quota
  namespace: flipsync-staging
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "30"
    services: "15"
    persistentvolumeclaims: "15"
    secrets: "50"
    configmaps: "50"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: flipsync-quota
  namespace: flipsync-dev
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "10"
    secrets: "30"
    configmaps: "30"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: flipsync-prod
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal-traffic
  namespace: flipsync-prod
spec:
  podSelector:
    matchLabels:
      app: flipsync
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: flipsync
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: flipsync
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-traffic
  namespace: flipsync-prod
spec:
  podSelector:
    matchLabels:
      app: flipsync
      component: api
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - podSelector:
        matchLabels:
          app: flipsync-ingress
  ports:
  - protocol: TCP
    port: 8080
