apiVersion: v1
kind: Secret
metadata:
  name: flipsync-db-credentials
  namespace: flipsync-prod
type: Opaque
stringData:
  username: flipsync_user
  password: ${DB_PASSWORD}
  url: postgresql://flipsync_user:${DB_PASSWORD}@flipsync-db:5432/flipsync
---
apiVersion: v1
kind: Secret
metadata:
  name: flipsync-redis-credentials
  namespace: flipsync-prod
type: Opaque
stringData:
  url: redis://flipsync-redis:6379/0
---
apiVersion: v1
kind: Secret
metadata:
  name: flipsync-qdrant-credentials
  namespace: flipsync-prod
type: Opaque
stringData:
  url: http://flipsync-qdrant:6333
---
apiVersion: v1
kind: Secret
metadata:
  name: flipsync-jwt-secret
  namespace: flipsync-prod
type: Opaque
stringData:
  secret: ${JWT_SECRET}
---
apiVersion: v1
kind: Secret
metadata:
  name: flipsync-amazon-credentials
  namespace: flipsync-prod
type: Opaque
stringData:
  api_key: ${AMAZON_API_KEY}
  api_secret: ${AMAZON_API_SECRET}
---
apiVersion: v1
kind: Secret
metadata:
  name: flipsync-ebay-credentials
  namespace: flipsync-prod
type: Opaque
stringData:
  api_key: ${EBAY_API_KEY}
  api_secret: ${EBAY_API_SECRET}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flipsync-api-sa
  namespace: flipsync-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flipsync-worker-sa
  namespace: flipsync-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flipsync-api-role
  namespace: flipsync-prod
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flipsync-worker-role
  namespace: flipsync-prod
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flipsync-api-rolebinding
  namespace: flipsync-prod
subjects:
- kind: ServiceAccount
  name: flipsync-api-sa
  namespace: flipsync-prod
roleRef:
  kind: Role
  name: flipsync-api-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flipsync-worker-rolebinding
  namespace: flipsync-prod
subjects:
- kind: ServiceAccount
  name: flipsync-worker-sa
  namespace: flipsync-prod
roleRef:
  kind: Role
  name: flipsync-worker-role
  apiGroup: rbac.authorization.k8s.io
