apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipsync-worker
  namespace: flipsync-prod
  labels:
    app: flipsync
    component: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flipsync
      component: worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flipsync
        component: worker
    spec:
      containers:
      - name: worker
        image: flipsync/worker:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: flipsync-db-credentials
              key: url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: flipsync-redis-credentials
              key: url
        - name: QDRANT_URL
          valueFrom:
            secretKeyRef:
              name: flipsync-qdrant-credentials
              key: url
        - name: AMAZON_SP_API_KEY
          valueFrom:
            secretKeyRef:
              name: flipsync-amazon-credentials
              key: api_key
        - name: AMAZON_SP_API_SECRET
          valueFrom:
            secretKeyRef:
              name: flipsync-amazon-credentials
              key: api_secret
        - name: EBAY_API_KEY
          valueFrom:
            secretKeyRef:
              name: flipsync-ebay-credentials
              key: api_key
        - name: EBAY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: flipsync-ebay-credentials
              key: api_secret
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep worker | grep -v grep
          initialDelaySeconds: 15
          periodSeconds: 20
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: flipsync-worker-sa
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flipsync-worker-hpa
  namespace: flipsync-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flipsync-worker
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: flipsync-worker-pdb
  namespace: flipsync-prod
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: flipsync
      component: worker
