apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipsync-agent-system
  namespace: flipsync-prod
  labels:
    app: flipsync
    tier: agent-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flipsync
      tier: agent-system
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flipsync
        tier: agent-system
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: flipsync-agent
      containers:
      - name: agent-system
        image: flipsync/agent-system:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        resources:
          requests:
            cpu: 2000m
            memory: 4Gi
          limits:
            cpu: 4000m
            memory: 8Gi
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: flipsync-db-credentials
              key: url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: flipsync-redis-credentials
              key: url
        - name: QDRANT_URL
          valueFrom:
            secretKeyRef:
              name: flipsync-qdrant-credentials
              key: url
        - name: AMAZON_SP_API_KEY
          valueFrom:
            secretKeyRef:
              name: flipsync-amazon-credentials
              key: api_key
        - name: AMAZON_SP_API_SECRET
          valueFrom:
            secretKeyRef:
              name: flipsync-amazon-credentials
              key: api_secret
        - name: EBAY_API_KEY
          valueFrom:
            secretKeyRef:
              name: flipsync-ebay-credentials
              key: api_key
        - name: EBAY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: flipsync-ebay-credentials
              key: api_secret
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: config
          mountPath: /app/config
        - name: cache
          mountPath: /app/cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: config
        configMap:
          name: flipsync-agent-config
      - name: cache
        persistentVolumeClaim:
          claimName: flipsync-agent-cache-pvc
