apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipsync-api-blue
  namespace: flipsync-prod
  labels:
    app: flipsync
    tier: api
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flipsync
      tier: api
      version: blue
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flipsync
        tier: api
        version: blue
    spec:
      serviceAccountName: flipsync-agent
      containers:
      - name: api
        image: flipsync/api:stable
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        - name: VERSION
          value: "blue"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: flipsync-db-credentials
              key: url
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: config
          mountPath: /app/config
      volumes:
      - name: tmp
        emptyDir: {}
      - name: config
        configMap:
          name: flipsync-api-config
