apiVersion: batch/v1
kind: CronJob
metadata:
  name: flipsync-db-backup-schedule
  namespace: flipsync-prod
spec:
  schedule: "0 2 * * *"  # Run daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: db-backup
            image: flipsync/db-backup:latest
            env:
            - name: BACKUP_TIMESTAMP
              value: "$(date +%Y%m%d-%H%M%S)"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: flipsync-db-credentials
                  key: url
            - name: BACKUP_BUCKET
              value: "flipsync-backups"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret_key
            command:
            - "/bin/sh"
            - "-c"
            - |
              pg_dump -Fc $DATABASE_URL > /tmp/flipsync-backup-$BACKUP_TIMESTAMP.dump
              aws s3 cp /tmp/flipsync-backup-$BACKUP_TIMESTAMP.dump s3://$BACKUP_BUCKET/
              # Cleanup old backups (keep last 30 days)
              aws s3 ls s3://$BACKUP_BUCKET/ | sort | head -n -30 | awk '{print $4}' | xargs -I {} aws s3 rm s3://$BACKUP_BUCKET/{}
          restartPolicy: OnFailure
