name: flipsync
description: FlipSync - Intelligent e-commerce management solution with AI agents
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  flutter_cache_manager: ^3.4.1
  photo_view: ^0.15.0
  uuid: ^4.5.1
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.4
  sqflite: ^2.3.3
  path: ^1.9.0
  url_launcher: ^6.3.1
  flutter_svg: ^2.1.0
  flutter_markdown: ^0.7.7+1
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^19.2.1
  connectivity_plus: ^6.1.4
  package_info_plus: ^8.3.0
  device_info_plus: ^10.1.2
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  rxdart: ^0.28.0
  logger: ^2.5.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  animated_text_kit: ^4.2.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.68.0
  syncfusion_flutter_gauges: ^26.2.14
  google_fonts: ^6.2.1
  flutter_slidable: ^3.1.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_animate: ^4.5.2
  timeago: ^3.7.0
  share_plus: ^11.0.0
  file_picker: ^10.1.9
  permission_handler: ^11.4.0
  flutter_html: ^3.0.0
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.1.5
  in_app_purchase: ^3.2.1
  firebase_core: ^3.12.1
  firebase_analytics: ^11.4.4
  firebase_messaging: ^15.2.4
  firebase_crashlytics: ^4.3.4
  firebase_performance: ^0.10.1+4
  firebase_remote_config: ^5.4.2
  google_sign_in: ^6.2.0
  sign_in_with_apple: ^6.1.4
  flutter_facebook_auth: ^7.1.1
  flutter_localizations:
    sdk: flutter
  injectable: ^2.5.0
  get_it: ^8.0.3
  dartz: ^0.10.1
  retrofit: ^4.4.2
  collection: ^1.18.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Core additional dependencies:
  freezed_annotation: ^2.4.1
  web_socket_channel: ^3.0.2

  # Additional dependencies:
  battery_plus: ^6.0.3
  encrypt: ^5.0.3
  sentry_flutter: ^8.14.2
  logging: ^1.2.0
  crypto: ^3.0.6
  synchronized: ^3.1.0

  # Isar database - official versions with version constraints
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  source_gen: ^1.5.0
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.10.0
  flutter_gen: ^5.10.0
  test: ^1.25.7
  bloc_test: ^10.0.0
  bloc: ^9.0.0

  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.0
  injectable_generator: ^2.6.2
  freezed: ^2.4.7
  
  # Compatible versions for Isar support
  build_runner: ^2.4.7  # Compatible with Dart 3.5.4
  retrofit_generator: ^8.2.0  # Latest version compatible with analyzer 6.x
  isar_generator: ^3.1.0+1   # Official version

# Override conflicting dependencies
dependency_overrides:
  analyzer: ^5.13.0  # Compatible with integration_test
  build_resolvers: ^2.4.2  # Compatible with Dart 3.5.4
  dart_style: ^2.3.8  # Ensure compatible version
  collection: 1.18.0  # Pin to version required by integration_test

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
    - assets/config/
    - assets/config/.env.production
    - graphics_files/
    - .env