// Mocks generated by Mockito 5.4.6 from annotations
// in flipsync_mobile/test/integration/user_journey_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i8;

import 'package:flipsync_mobile/core/network/api_service.dart' as _i7;
import 'package:flipsync_mobile/core/network/websocket_service.dart' as _i9;
import 'package:flipsync_mobile/data/models/decision_model.dart' as _i2;
import 'package:flipsync_mobile/data/repositories/auth_repository.dart' as _i3;
import 'package:flipsync_mobile/data/repositories/decisions_repository.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDecisionsResponse_0 extends _i1.SmartFake
    implements _i2.DecisionsResponse {
  _FakeDecisionsResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeComplianceMetrics_1 extends _i1.SmartFake
    implements _i2.ComplianceMetrics {
  _FakeComplianceMetrics_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Map<String, dynamic>> startEbayOAuth(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#startEbayOAuth, [userId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> handleOAuthCallback({
    required String? code,
    required String? state,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#handleOAuthCallback, [], {
              #code: code,
              #state: state,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>?> getAuthStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getAuthStatus, []),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<Map<String, dynamic>> refreshTokens(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshTokens, [userId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getStoredUserId() =>
      (super.noSuchMethod(
            Invocation.method(#getStoredUserId, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String> getEbayOAuthUrl() =>
      (super.noSuchMethod(
            Invocation.method(#getEbayOAuthUrl, []),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#getEbayOAuthUrl, []),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<Map<String, dynamic>> exchangeCodeForTokens(
    String? code,
    String? state,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#exchangeCodeForTokens, [code, state]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> refreshEbayTokens(String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#refreshEbayTokens, [refreshToken]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> storeTokens(
    String? accessToken,
    String? refreshToken,
    int? expiresIn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#storeTokens, [
              accessToken,
              refreshToken,
              expiresIn,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getStoredTokens() =>
      (super.noSuchMethod(
            Invocation.method(#getStoredTokens, []),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> clearTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearTokens, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> validateToken(String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#validateToken, [accessToken]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [DecisionsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDecisionsRepository extends _i1.Mock
    implements _i6.DecisionsRepository {
  MockDecisionsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DecisionsResponse> getDecisions({
    int? limit = 50,
    int? offset = 0,
    String? agentId,
    String? decisionType,
    String? status,
    bool? llmFreeOnly = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDecisions, [], {
              #limit: limit,
              #offset: offset,
              #agentId: agentId,
              #decisionType: decisionType,
              #status: status,
              #llmFreeOnly: llmFreeOnly,
            }),
            returnValue: _i4.Future<_i2.DecisionsResponse>.value(
              _FakeDecisionsResponse_0(
                this,
                Invocation.method(#getDecisions, [], {
                  #limit: limit,
                  #offset: offset,
                  #agentId: agentId,
                  #decisionType: decisionType,
                  #status: status,
                  #llmFreeOnly: llmFreeOnly,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.DecisionsResponse>);

  @override
  _i4.Future<Map<String, dynamic>> getDecisionAnalytics({
    int? timeRangeHours = 24,
    String? agentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDecisionAnalytics, [], {
              #timeRangeHours: timeRangeHours,
              #agentId: agentId,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<_i2.DecisionModel>> getDecisionsByAgent(String? agentId) =>
      (super.noSuchMethod(
            Invocation.method(#getDecisionsByAgent, [agentId]),
            returnValue: _i4.Future<List<_i2.DecisionModel>>.value(
              <_i2.DecisionModel>[],
            ),
          )
          as _i4.Future<List<_i2.DecisionModel>>);

  @override
  _i4.Future<List<_i2.DecisionModel>> getRecentDecisions({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentDecisions, [], {#limit: limit}),
            returnValue: _i4.Future<List<_i2.DecisionModel>>.value(
              <_i2.DecisionModel>[],
            ),
          )
          as _i4.Future<List<_i2.DecisionModel>>);

  @override
  _i4.Future<List<_i2.DecisionModel>> getLlmFreeDecisions({int? limit = 50}) =>
      (super.noSuchMethod(
            Invocation.method(#getLlmFreeDecisions, [], {#limit: limit}),
            returnValue: _i4.Future<List<_i2.DecisionModel>>.value(
              <_i2.DecisionModel>[],
            ),
          )
          as _i4.Future<List<_i2.DecisionModel>>);

  @override
  _i4.Future<_i2.ComplianceMetrics> getComplianceMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getComplianceMetrics, []),
            returnValue: _i4.Future<_i2.ComplianceMetrics>.value(
              _FakeComplianceMetrics_1(
                this,
                Invocation.method(#getComplianceMetrics, []),
              ),
            ),
          )
          as _i4.Future<_i2.ComplianceMetrics>);

  @override
  _i4.Future<Map<String, dynamic>> getPerformanceSummary() =>
      (super.noSuchMethod(
            Invocation.method(#getPerformanceSummary, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAgentDecisions(
    String? agentId, {
    int? limit,
    int? offset,
    String? decisionType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getAgentDecisions,
              [agentId],
              {#limit: limit, #offset: offset, #decisionType: decisionType},
            ),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>> submitDecisionFeedback(
    String? decisionId,
    Map<String, dynamic>? feedback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitDecisionFeedback, [decisionId, feedback]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> requestAgentDecision(
    String? agentId,
    Map<String, dynamic>? requestData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#requestAgentDecision, [agentId, requestData]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getLatestDecisions({
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestDecisions, [], {#limit: limit}),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>> getDecisionStatus(String? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#getDecisionStatus, [requestId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i7.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Map<String, dynamic>> triggerAgent({
    required String? agentId,
    required String? taskType,
    required Map<String, dynamic>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#triggerAgent, [], {
              #agentId: agentId,
              #taskType: taskType,
              #parameters: parameters,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getAgentStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getAgentStatus, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getCacheStats() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheStats, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> sendChatMessage({
    required String? message,
    required String? userId,
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendChatMessage, [], {
              #message: message,
              #userId: userId,
              #context: context,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> startEbayOAuth({
    required String? userId,
    List<String>? scopes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startEbayOAuth, [], {
              #userId: userId,
              #scopes: scopes,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> handleEbayOAuthCallback({
    required String? code,
    required String? state,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#handleEbayOAuthCallback, [], {
              #code: code,
              #state: state,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getEbayOAuthStatus(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getEbayOAuthStatus, [userId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> refreshEbayOAuthTokens(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshEbayOAuthTokens, [userId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> revokeEbayOAuthTokens(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#revokeEbayOAuthTokens, [userId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getDecisions({
    int? limit = 50,
    int? offset = 0,
    String? agentId,
    String? decisionType,
    String? status,
    bool? llmFreeOnly = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDecisions, [], {
              #limit: limit,
              #offset: offset,
              #agentId: agentId,
              #decisionType: decisionType,
              #status: status,
              #llmFreeOnly: llmFreeOnly,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getDecisionAnalytics({
    int? timeRangeHours = 24,
    String? agentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDecisionAnalytics, [], {
              #timeRangeHours: timeRangeHours,
              #agentId: agentId,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> createConversation({
    required String? title,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createConversation, [], {
              #title: title,
              #metadata: metadata,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getConversations({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getConversations, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> sendMessageToConversation({
    required String? conversationId,
    required String? content,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessageToConversation, [], {
              #conversationId: conversationId,
              #content: content,
              #metadata: metadata,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getChatMessages({
    required String? conversationId,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChatMessages, [], {
              #conversationId: conversationId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getAnalyticsSummary({
    String? timeRange,
    List<String>? agentIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAnalyticsSummary, [], {
              #timeRange: timeRange,
              #agentIds: agentIds,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getAgentPerformanceMetrics({
    String? agentId,
    String? timeRange,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAgentPerformanceMetrics, [], {
              #agentId: agentId,
              #timeRange: timeRange,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getSystemHealthMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getSystemHealthMetrics, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getBusinessMetrics({
    String? timeRange,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBusinessMetrics, [], {
              #timeRange: timeRange,
              #category: category,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getTimeSeriesData({
    required String? metric,
    String? timeRange,
    String? agentId,
    String? granularity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTimeSeriesData, [], {
              #metric: metric,
              #timeRange: timeRange,
              #agentId: agentId,
              #granularity: granularity,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> exportAnalyticsData({
    required String? format,
    String? timeRange,
    List<String>? metrics,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#exportAnalyticsData, [], {
              #format: format,
              #timeRange: timeRange,
              #metrics: metrics,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> get(
    String? endpoint, {
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [endpoint],
              {#queryParameters: queryParameters, #headers: headers},
            ),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> post(
    String? endpoint, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [endpoint],
              {
                #data: data,
                #queryParameters: queryParameters,
                #headers: headers,
              },
            ),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> put(
    String? endpoint, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [endpoint],
              {
                #data: data,
                #queryParameters: queryParameters,
                #headers: headers,
              },
            ),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> delete(
    String? endpoint, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [endpoint],
              {
                #data: data,
                #queryParameters: queryParameters,
                #headers: headers,
              },
            ),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> identifyProductFromBarcode(
    String? barcode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#identifyProductFromBarcode, [barcode]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> processProductPhotos({
    required List<String>? photoUrls,
    bool? enableOcr = true,
    bool? enableVisionApi = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#processProductPhotos, [], {
              #photoUrls: photoUrls,
              #enableOcr: enableOcr,
              #enableVisionApi: enableVisionApi,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> createProductManually(
    Map<String, dynamic>? productData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createProductManually, [productData]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> uploadProductPhoto({
    required _i8.File? file,
    required String? filename,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProductPhoto, [], {
              #file: file,
              #filename: filename,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> requestAgentDecision({
    required String? agentId,
    required Map<String, dynamic>? requestData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestAgentDecision, [], {
              #agentId: agentId,
              #requestData: requestData,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getProductCreationAnalytics() =>
      (super.noSuchMethod(
            Invocation.method(#getProductCreationAnalytics, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [WebSocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketService extends _i1.Mock implements _i9.WebSocketService {
  MockWebSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<Map<String, dynamic>> get messageStream =>
      (super.noSuchMethod(
            Invocation.getter(#messageStream),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i4.Future<void> connectToAgentShowcase() =>
      (super.noSuchMethod(
            Invocation.method(#connectToAgentShowcase, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> connectToAgentStatus({String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#connectToAgentStatus, [], {#token: token}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> connectToUnifiedChat({required String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#connectToUnifiedChat, [], {#token: token}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> connectToMonitoring() =>
      (super.noSuchMethod(
            Invocation.method(#connectToMonitoring, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> connectToEbayOAuth(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#connectToEbayOAuth, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendMessage(Map<String, dynamic>? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [message]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addEventListener(
    String? eventType,
    dynamic Function(Map<String, dynamic>)? callback,
  ) => super.noSuchMethod(
    Invocation.method(#addEventListener, [eventType, callback]),
    returnValueForMissingStub: null,
  );

  @override
  void removeEventListener(
    String? eventType,
    dynamic Function(Map<String, dynamic>)? callback,
  ) => super.noSuchMethod(
    Invocation.method(#removeEventListener, [eventType, callback]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
