apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-database-access
  namespace: flipsync-prod
spec:
  podSelector:
    matchLabels:
      app: flipsync
      tier: database
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: flipsync
    ports:
    - protocol: TCP
      port: 5432
