// Mocks generated by Mockito 5.4.6 from annotations
// in flipsync_mobile/test/unit/blocs/decisions_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flipsync_mobile/core/network/websocket_service.dart' as _i5;
import 'package:flipsync_mobile/data/models/decision_model.dart' as _i2;
import 'package:flipsync_mobile/data/repositories/decisions_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDecisionsResponse_0 extends _i1.SmartFake
    implements _i2.DecisionsResponse {
  _FakeDecisionsResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeComplianceMetrics_1 extends _i1.SmartFake
    implements _i2.ComplianceMetrics {
  _FakeComplianceMetrics_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DecisionsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDecisionsRepository extends _i1.Mock
    implements _i3.DecisionsRepository {
  MockDecisionsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DecisionsResponse> getDecisions({
    int? limit = 50,
    int? offset = 0,
    String? agentId,
    String? decisionType,
    String? status,
    bool? llmFreeOnly = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDecisions, [], {
              #limit: limit,
              #offset: offset,
              #agentId: agentId,
              #decisionType: decisionType,
              #status: status,
              #llmFreeOnly: llmFreeOnly,
            }),
            returnValue: _i4.Future<_i2.DecisionsResponse>.value(
              _FakeDecisionsResponse_0(
                this,
                Invocation.method(#getDecisions, [], {
                  #limit: limit,
                  #offset: offset,
                  #agentId: agentId,
                  #decisionType: decisionType,
                  #status: status,
                  #llmFreeOnly: llmFreeOnly,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.DecisionsResponse>);

  @override
  _i4.Future<Map<String, dynamic>> getDecisionAnalytics({
    int? timeRangeHours = 24,
    String? agentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDecisionAnalytics, [], {
              #timeRangeHours: timeRangeHours,
              #agentId: agentId,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<_i2.DecisionModel>> getDecisionsByAgent(String? agentId) =>
      (super.noSuchMethod(
            Invocation.method(#getDecisionsByAgent, [agentId]),
            returnValue: _i4.Future<List<_i2.DecisionModel>>.value(
              <_i2.DecisionModel>[],
            ),
          )
          as _i4.Future<List<_i2.DecisionModel>>);

  @override
  _i4.Future<List<_i2.DecisionModel>> getRecentDecisions({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentDecisions, [], {#limit: limit}),
            returnValue: _i4.Future<List<_i2.DecisionModel>>.value(
              <_i2.DecisionModel>[],
            ),
          )
          as _i4.Future<List<_i2.DecisionModel>>);

  @override
  _i4.Future<List<_i2.DecisionModel>> getLlmFreeDecisions({int? limit = 50}) =>
      (super.noSuchMethod(
            Invocation.method(#getLlmFreeDecisions, [], {#limit: limit}),
            returnValue: _i4.Future<List<_i2.DecisionModel>>.value(
              <_i2.DecisionModel>[],
            ),
          )
          as _i4.Future<List<_i2.DecisionModel>>);

  @override
  _i4.Future<_i2.ComplianceMetrics> getComplianceMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getComplianceMetrics, []),
            returnValue: _i4.Future<_i2.ComplianceMetrics>.value(
              _FakeComplianceMetrics_1(
                this,
                Invocation.method(#getComplianceMetrics, []),
              ),
            ),
          )
          as _i4.Future<_i2.ComplianceMetrics>);

  @override
  _i4.Future<Map<String, dynamic>> getPerformanceSummary() =>
      (super.noSuchMethod(
            Invocation.method(#getPerformanceSummary, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAgentDecisions(
    String? agentId, {
    int? limit,
    int? offset,
    String? decisionType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getAgentDecisions,
              [agentId],
              {#limit: limit, #offset: offset, #decisionType: decisionType},
            ),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>> submitDecisionFeedback(
    String? decisionId,
    Map<String, dynamic>? feedback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitDecisionFeedback, [decisionId, feedback]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> requestAgentDecision(
    String? agentId,
    Map<String, dynamic>? requestData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#requestAgentDecision, [agentId, requestData]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getLatestDecisions({
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestDecisions, [], {#limit: limit}),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>> getDecisionStatus(String? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#getDecisionStatus, [requestId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [WebSocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketService extends _i1.Mock implements _i5.WebSocketService {
  MockWebSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<Map<String, dynamic>> get messageStream =>
      (super.noSuchMethod(
            Invocation.getter(#messageStream),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i4.Future<void> connectToAgentShowcase() =>
      (super.noSuchMethod(
            Invocation.method(#connectToAgentShowcase, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> connectToAgentStatus({String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#connectToAgentStatus, [], {#token: token}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> connectToUnifiedChat({required String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#connectToUnifiedChat, [], {#token: token}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> connectToMonitoring() =>
      (super.noSuchMethod(
            Invocation.method(#connectToMonitoring, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> connectToEbayOAuth(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#connectToEbayOAuth, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendMessage(Map<String, dynamic>? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [message]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addEventListener(
    String? eventType,
    dynamic Function(Map<String, dynamic>)? callback,
  ) => super.noSuchMethod(
    Invocation.method(#addEventListener, [eventType, callback]),
    returnValueForMissingStub: null,
  );

  @override
  void removeEventListener(
    String? eventType,
    dynamic Function(Map<String, dynamic>)? callback,
  ) => super.noSuchMethod(
    Invocation.method(#removeEventListener, [eventType, callback]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
