// Mocks generated by Mockito 5.4.6 from annotations
// in flipsync_mobile/test/widget/pages/agents_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flipsync_mobile/presentation/blocs/decisions/decisions_bloc.dart'
    as _i3;
import 'package:flipsync_mobile/presentation/blocs/decisions/decisions_event.dart'
    as _i5;
import 'package:flipsync_mobile/presentation/blocs/decisions/decisions_state.dart'
    as _i2;
import 'package:flutter_bloc/flutter_bloc.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDecisionsState_0 extends _i1.SmartFake
    implements _i2.DecisionsState {
  _FakeDecisionsState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DecisionsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockDecisionsBloc extends _i1.Mock implements _i3.DecisionsBloc {
  MockDecisionsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasDecisions =>
      (super.noSuchMethod(Invocation.getter(#hasDecisions), returnValue: false)
          as bool);

  @override
  List<dynamic> get currentDecisions =>
      (super.noSuchMethod(
            Invocation.getter(#currentDecisions),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  bool get canLoadMore =>
      (super.noSuchMethod(Invocation.getter(#canLoadMore), returnValue: false)
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isLoadingMore =>
      (super.noSuchMethod(Invocation.getter(#isLoadingMore), returnValue: false)
          as bool);

  @override
  bool get isRefreshing =>
      (super.noSuchMethod(Invocation.getter(#isRefreshing), returnValue: false)
          as bool);

  @override
  bool get isWebSocketConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isWebSocketConnected),
            returnValue: false,
          )
          as bool);

  @override
  bool get isWebSocketConnecting =>
      (super.noSuchMethod(
            Invocation.getter(#isWebSocketConnecting),
            returnValue: false,
          )
          as bool);

  @override
  List<String> get webSocketCapabilities =>
      (super.noSuchMethod(
            Invocation.getter(#webSocketCapabilities),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i2.DecisionsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeDecisionsState_0(this, Invocation.getter(#state)),
          )
          as _i2.DecisionsState);

  @override
  _i4.Stream<_i2.DecisionsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i2.DecisionsState>.empty(),
          )
          as _i4.Stream<_i2.DecisionsState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void loadDecisions() => super.noSuchMethod(
    Invocation.method(#loadDecisions, []),
    returnValueForMissingStub: null,
  );

  @override
  void loadDecisionsForAgent(String? agentId) => super.noSuchMethod(
    Invocation.method(#loadDecisionsForAgent, [agentId]),
    returnValueForMissingStub: null,
  );

  @override
  void loadLlmFreeDecisions() => super.noSuchMethod(
    Invocation.method(#loadLlmFreeDecisions, []),
    returnValueForMissingStub: null,
  );

  @override
  void loadMoreDecisions() => super.noSuchMethod(
    Invocation.method(#loadMoreDecisions, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshDecisions() => super.noSuchMethod(
    Invocation.method(#refreshDecisions, []),
    returnValueForMissingStub: null,
  );

  @override
  void applyFilters({
    String? agentId,
    String? decisionType,
    String? status,
    bool? llmFreeOnly = false,
  }) => super.noSuchMethod(
    Invocation.method(#applyFilters, [], {
      #agentId: agentId,
      #decisionType: decisionType,
      #status: status,
      #llmFreeOnly: llmFreeOnly,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void loadAnalytics({int? timeRangeHours = 24, String? agentId}) =>
      super.noSuchMethod(
        Invocation.method(#loadAnalytics, [], {
          #timeRangeHours: timeRangeHours,
          #agentId: agentId,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void connectWebSocket() => super.noSuchMethod(
    Invocation.method(#connectWebSocket, []),
    returnValueForMissingStub: null,
  );

  @override
  void disconnectWebSocket() => super.noSuchMethod(
    Invocation.method(#disconnectWebSocket, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void add(_i5.DecisionsEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i5.DecisionsEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i2.DecisionsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i5.DecisionsEvent>(
    _i6.EventHandler<E, _i2.DecisionsState>? handler, {
    _i6.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i6.Transition<_i5.DecisionsEvent, _i2.DecisionsState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i6.Change<_i2.DecisionsState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
