// Mocks generated by Mockito 5.4.6 from annotations
// in flipsync_mobile/test/widget/pages/dashboard_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flipsync_mobile/presentation/blocs/analytics/analytics_bloc.dart'
    as _i8;
import 'package:flipsync_mobile/presentation/blocs/analytics/analytics_event.dart'
    as _i9;
import 'package:flipsync_mobile/presentation/blocs/analytics/analytics_state.dart'
    as _i3;
import 'package:flipsync_mobile/presentation/blocs/decisions/decisions_bloc.dart'
    as _i4;
import 'package:flipsync_mobile/presentation/blocs/decisions/decisions_event.dart'
    as _i6;
import 'package:flipsync_mobile/presentation/blocs/decisions/decisions_state.dart'
    as _i2;
import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDecisionsState_0 extends _i1.SmartFake
    implements _i2.DecisionsState {
  _FakeDecisionsState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAnalyticsState_1 extends _i1.SmartFake
    implements _i3.AnalyticsState {
  _FakeAnalyticsState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DecisionsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockDecisionsBloc extends _i1.Mock implements _i4.DecisionsBloc {
  MockDecisionsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasDecisions =>
      (super.noSuchMethod(Invocation.getter(#hasDecisions), returnValue: false)
          as bool);

  @override
  List<dynamic> get currentDecisions =>
      (super.noSuchMethod(
            Invocation.getter(#currentDecisions),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  bool get canLoadMore =>
      (super.noSuchMethod(Invocation.getter(#canLoadMore), returnValue: false)
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isLoadingMore =>
      (super.noSuchMethod(Invocation.getter(#isLoadingMore), returnValue: false)
          as bool);

  @override
  bool get isRefreshing =>
      (super.noSuchMethod(Invocation.getter(#isRefreshing), returnValue: false)
          as bool);

  @override
  bool get isWebSocketConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isWebSocketConnected),
            returnValue: false,
          )
          as bool);

  @override
  bool get isWebSocketConnecting =>
      (super.noSuchMethod(
            Invocation.getter(#isWebSocketConnecting),
            returnValue: false,
          )
          as bool);

  @override
  List<String> get webSocketCapabilities =>
      (super.noSuchMethod(
            Invocation.getter(#webSocketCapabilities),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i2.DecisionsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeDecisionsState_0(this, Invocation.getter(#state)),
          )
          as _i2.DecisionsState);

  @override
  _i5.Stream<_i2.DecisionsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i2.DecisionsState>.empty(),
          )
          as _i5.Stream<_i2.DecisionsState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void loadDecisions() => super.noSuchMethod(
    Invocation.method(#loadDecisions, []),
    returnValueForMissingStub: null,
  );

  @override
  void loadDecisionsForAgent(String? agentId) => super.noSuchMethod(
    Invocation.method(#loadDecisionsForAgent, [agentId]),
    returnValueForMissingStub: null,
  );

  @override
  void loadLlmFreeDecisions() => super.noSuchMethod(
    Invocation.method(#loadLlmFreeDecisions, []),
    returnValueForMissingStub: null,
  );

  @override
  void loadMoreDecisions() => super.noSuchMethod(
    Invocation.method(#loadMoreDecisions, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshDecisions() => super.noSuchMethod(
    Invocation.method(#refreshDecisions, []),
    returnValueForMissingStub: null,
  );

  @override
  void applyFilters({
    String? agentId,
    String? decisionType,
    String? status,
    bool? llmFreeOnly = false,
  }) => super.noSuchMethod(
    Invocation.method(#applyFilters, [], {
      #agentId: agentId,
      #decisionType: decisionType,
      #status: status,
      #llmFreeOnly: llmFreeOnly,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void loadAnalytics({int? timeRangeHours = 24, String? agentId}) =>
      super.noSuchMethod(
        Invocation.method(#loadAnalytics, [], {
          #timeRangeHours: timeRangeHours,
          #agentId: agentId,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void connectWebSocket() => super.noSuchMethod(
    Invocation.method(#connectWebSocket, []),
    returnValueForMissingStub: null,
  );

  @override
  void disconnectWebSocket() => super.noSuchMethod(
    Invocation.method(#disconnectWebSocket, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void add(_i6.DecisionsEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i6.DecisionsEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i2.DecisionsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i6.DecisionsEvent>(
    _i7.EventHandler<E, _i2.DecisionsState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i7.Transition<_i6.DecisionsEvent, _i2.DecisionsState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i7.Change<_i2.DecisionsState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AnalyticsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsBloc extends _i1.Mock implements _i8.AnalyticsBloc {
  MockAnalyticsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isWebSocketConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isWebSocketConnected),
            returnValue: false,
          )
          as bool);

  @override
  _i3.AnalyticsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAnalyticsState_1(this, Invocation.getter(#state)),
          )
          as _i3.AnalyticsState);

  @override
  _i5.Stream<_i3.AnalyticsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i3.AnalyticsState>.empty(),
          )
          as _i5.Stream<_i3.AnalyticsState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void loadSummary({String? timeRange, List<String>? agentIds}) =>
      super.noSuchMethod(
        Invocation.method(#loadSummary, [], {
          #timeRange: timeRange,
          #agentIds: agentIds,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void loadAgentPerformance({String? agentId, String? timeRange}) =>
      super.noSuchMethod(
        Invocation.method(#loadAgentPerformance, [], {
          #agentId: agentId,
          #timeRange: timeRange,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void loadSystemHealth() => super.noSuchMethod(
    Invocation.method(#loadSystemHealth, []),
    returnValueForMissingStub: null,
  );

  @override
  void loadBusinessMetrics({String? timeRange, String? category}) =>
      super.noSuchMethod(
        Invocation.method(#loadBusinessMetrics, [], {
          #timeRange: timeRange,
          #category: category,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void loadDashboard({String? timeRange}) => super.noSuchMethod(
    Invocation.method(#loadDashboard, [], {#timeRange: timeRange}),
    returnValueForMissingStub: null,
  );

  @override
  void changeTimeRange(String? timeRange) => super.noSuchMethod(
    Invocation.method(#changeTimeRange, [timeRange]),
    returnValueForMissingStub: null,
  );

  @override
  void exportData(String? format, {String? timeRange, List<String>? metrics}) =>
      super.noSuchMethod(
        Invocation.method(
          #exportData,
          [format],
          {#timeRange: timeRange, #metrics: metrics},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void connectWebSocket() => super.noSuchMethod(
    Invocation.method(#connectWebSocket, []),
    returnValueForMissingStub: null,
  );

  @override
  void disconnectWebSocket() => super.noSuchMethod(
    Invocation.method(#disconnectWebSocket, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshAll() => super.noSuchMethod(
    Invocation.method(#refreshAll, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void add(_i9.AnalyticsEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i9.AnalyticsEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.AnalyticsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i9.AnalyticsEvent>(
    _i7.EventHandler<E, _i3.AnalyticsState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i7.Transition<_i9.AnalyticsEvent, _i3.AnalyticsState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i7.Change<_i3.AnalyticsState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
