apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flipsync-agent-rolebinding
  namespace: flipsync-prod
subjects:
- kind: ServiceAccount
  name: flipsync-agent
  namespace: flipsync-prod
roleRef:
  kind: Role
  name: flipsync-agent-role
  apiGroup: rbac.authorization.k8s.io
