apiVersion: v1
kind: ConfigMap
metadata:
  name: flipsync-grafana-datasources
  namespace: flipsync-prod
  labels:
    app: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090
      access: proxy
      isDefault: true
