apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: flipsync-prod
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP
