#!/bin/bash

# FlipSync SSL Certificate Setup Script
# This script sets up Let's Encrypt SSL certificates and configures Nginx with HTTPS

set -e  # Exit on any error

# Configuration
DOMAIN="flipsyncai.com"
WWW_DOMAIN="www.flipsyncai.com"
EMAIL="developer@flipsync.com"  # Change this to your email
NGINX_CONFIG_DIR="/etc/nginx"
SITES_AVAILABLE="$NGINX_CONFIG_DIR/sites-available"
SITES_ENABLED="$NGINX_CONFIG_DIR/sites-enabled"
BACKEND_PORT="8000"

echo "🔐 FlipSync SSL Certificate Setup"
echo "=================================="
echo "Domain: $DOMAIN"
echo "WWW Domain: $WWW_DOMAIN"
echo "Email: $EMAIL"
echo "Backend Port: $BACKEND_PORT"
echo ""

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo "❌ This script must be run as root (use sudo)"
   exit 1
fi

# Update system packages
echo "📦 Updating system packages..."
apt update -y
apt upgrade -y

# Install required packages
echo "📦 Installing required packages..."
apt install -y nginx certbot python3-certbot-nginx ufw curl

# Check if Nginx is installed
if ! command -v nginx &> /dev/null; then
    echo "❌ Nginx installation failed"
    exit 1
fi

echo "✅ Nginx installed successfully"

# Stop Nginx temporarily for certificate generation
echo "🔄 Stopping Nginx temporarily..."
systemctl stop nginx

# Configure UFW firewall
echo "🔥 Configuring firewall..."
ufw --force enable
ufw allow 'Nginx Full'
ufw allow OpenSSH
ufw allow 8000  # Backend port
ufw status

# Create initial Nginx configuration (HTTP only for certificate generation)
echo "📝 Creating initial Nginx configuration..."
cat > "$SITES_AVAILABLE/flipsyncai" << EOF
# FlipSync Initial Configuration (HTTP only for SSL setup)
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN $WWW_DOMAIN;

    # Let's Encrypt ACME Challenge
    location /.well-known/acme-challenge/ {
        root /var/www/html;
        allow all;
    }

    # Temporary redirect to backend for testing
    location / {
        proxy_pass http://127.0.0.1:$BACKEND_PORT;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

# Enable the site
echo "🔗 Enabling Nginx site..."
ln -sf "$SITES_AVAILABLE/flipsyncai" "$SITES_ENABLED/"

# Remove default Nginx site if it exists
if [ -f "$SITES_ENABLED/default" ]; then
    rm "$SITES_ENABLED/default"
    echo "✅ Removed default Nginx site"
fi

# Test Nginx configuration
echo "🧪 Testing Nginx configuration..."
nginx -t

if [ $? -ne 0 ]; then
    echo "❌ Nginx configuration test failed"
    exit 1
fi

# Start Nginx
echo "🚀 Starting Nginx..."
systemctl start nginx
systemctl enable nginx

# Wait a moment for Nginx to start
sleep 2

# Test HTTP access
echo "🧪 Testing HTTP access..."
HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://$DOMAIN" || echo "000")
if [ "$HTTP_STATUS" = "200" ] || [ "$HTTP_STATUS" = "405" ]; then
    echo "✅ HTTP access working (Status: $HTTP_STATUS)"
else
    echo "⚠️  HTTP access returned status: $HTTP_STATUS (may be normal)"
fi

# Generate SSL certificates using Certbot
echo "🔐 Generating SSL certificates with Let's Encrypt..."
echo "This may take a few minutes..."

# Use certbot with nginx plugin
certbot --nginx \
    --non-interactive \
    --agree-tos \
    --email "$EMAIL" \
    --domains "$DOMAIN,$WWW_DOMAIN" \
    --redirect

if [ $? -ne 0 ]; then
    echo "❌ SSL certificate generation failed"
    echo "Please check the error messages above"
    exit 1
fi

echo "✅ SSL certificates generated successfully"

# Create the full production Nginx configuration
echo "📝 Creating production Nginx configuration with SSL..."
cat > "$SITES_AVAILABLE/flipsyncai" << EOF
# FlipSync Production Configuration with SSL
# Generated by setup-ssl-certificates.sh

# Rate limiting
limit_req_zone \$binary_remote_addr zone=api_limit:10m rate=10r/s;
limit_req_zone \$binary_remote_addr zone=general_limit:10m rate=30r/s;

# HTTP to HTTPS Redirect
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN $WWW_DOMAIN;
    
    # Let's Encrypt ACME Challenge
    location /.well-known/acme-challenge/ {
        root /var/www/html;
        allow all;
    }
    
    # Redirect all HTTP to HTTPS
    location / {
        return 301 https://\$server_name\$request_uri;
    }
}

# HTTPS Server - Main Configuration
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $DOMAIN $WWW_DOMAIN;

    # SSL Configuration (managed by Certbot)
    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Security Headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options DENY always;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    # Rate limiting
    limit_req zone=general_limit burst=20 nodelay;

    # eBay OAuth Callback - CRITICAL for eBay integration
    location /ebay-oauth {
        proxy_pass http://127.0.0.1:$BACKEND_PORT/ebay-oauth;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
    }

    # API Routes
    location /api/ {
        proxy_pass http://127.0.0.1:$BACKEND_PORT;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        
        # Rate limiting for API
        limit_req zone=api_limit burst=10 nodelay;
    }

    # WebSocket Support
    location /ws/ {
        proxy_pass http://127.0.0.1:$BACKEND_PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    # Documentation and Health Checks
    location ~ ^/(docs|redoc|openapi.json|health) {
        proxy_pass http://127.0.0.1:$BACKEND_PORT;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # Default location - serve Flutter web app or proxy to backend
    location / {
        # Try to serve static files first, then proxy to backend
        try_files \$uri \$uri/ @backend;
    }

    # Backend proxy fallback
    location @backend {
        proxy_pass http://127.0.0.1:$BACKEND_PORT;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # Static file serving (for future Flutter web app)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)\$ {
        root /var/www/flipsyncai.com;
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files \$uri @backend;
    }
}
EOF

# Test the new configuration
echo "🧪 Testing new Nginx configuration..."
nginx -t

if [ $? -ne 0 ]; then
    echo "❌ New Nginx configuration test failed"
    exit 1
fi

# Reload Nginx with new configuration
echo "🔄 Reloading Nginx with SSL configuration..."
systemctl reload nginx

# Wait for reload
sleep 2

# Test HTTPS access
echo "🧪 Testing HTTPS access..."
HTTPS_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://$DOMAIN" || echo "000")
if [ "$HTTPS_STATUS" = "200" ] || [ "$HTTPS_STATUS" = "405" ]; then
    echo "✅ HTTPS access working (Status: $HTTPS_STATUS)"
else
    echo "⚠️  HTTPS access returned status: $HTTPS_STATUS"
fi

# Test eBay OAuth endpoint specifically
echo "🧪 Testing eBay OAuth endpoint..."
OAUTH_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://$DOMAIN/ebay-oauth?test=1" || echo "000")
if [ "$OAUTH_STATUS" = "200" ]; then
    echo "✅ eBay OAuth endpoint working (Status: $OAUTH_STATUS)"
else
    echo "⚠️  eBay OAuth endpoint returned status: $OAUTH_STATUS"
fi

# Set up automatic certificate renewal
echo "🔄 Setting up automatic certificate renewal..."
systemctl enable certbot.timer
systemctl start certbot.timer

# Test certificate renewal (dry run)
echo "🧪 Testing certificate renewal (dry run)..."
certbot renew --dry-run

if [ $? -eq 0 ]; then
    echo "✅ Certificate renewal test passed"
else
    echo "⚠️  Certificate renewal test failed (may need manual attention)"
fi

# Create web directory for future use
mkdir -p /var/www/flipsyncai.com
chown -R www-data:www-data /var/www/flipsyncai.com

echo ""
echo "🎉 SSL Setup Complete!"
echo "====================="
echo "✅ SSL certificates installed for $DOMAIN and $WWW_DOMAIN"
echo "✅ Nginx configured with HTTPS"
echo "✅ HTTP to HTTPS redirect enabled"
echo "✅ eBay OAuth endpoint configured at https://$DOMAIN/ebay-oauth"
echo "✅ Automatic certificate renewal enabled"
echo ""
echo "🔗 Test URLs:"
echo "   • https://$DOMAIN"
echo "   • https://$WWW_DOMAIN"
echo "   • https://$DOMAIN/ebay-oauth"
echo "   • https://$DOMAIN/docs"
echo ""
echo "📝 Next Steps:"
echo "   1. Test the eBay OAuth flow with your React app"
echo "   2. Update eBay Developer Console if needed"
echo "   3. Deploy your Flutter web app to /var/www/flipsyncai.com"
echo ""
echo "🔧 Configuration files:"
echo "   • Nginx: $SITES_AVAILABLE/flipsyncai"
echo "   • SSL Certs: /etc/letsencrypt/live/$DOMAIN/"
echo ""
