apiVersion: v1
kind: LimitRange
metadata:
  name: agent-limit-range
  namespace: flipsync-prod
spec:
  limits:
  - type: Container
    default:
      cpu: 2000m
      memory: 2Gi
    defaultRequest:
      cpu: 1000m
      memory: 1Gi
    max:
      cpu: 8
      memory: 16Gi
    min:
      cpu: 500m
      memory: 512Mi
  - type: PersistentVolumeClaim
    max:
      storage: 500Gi
    min:
      storage: 10Gi
