apiVersion: v1
kind: LimitRange
metadata:
  name: agent-limit-range
  namespace: flipsync-staging
spec:
  limits:
  - type: Container
    default:
      cpu: 1000m
      memory: 1Gi
    defaultRequest:
      cpu: 500m
      memory: 512Mi
    max:
      cpu: 4
      memory: 8Gi
    min:
      cpu: 200m
      memory: 256Mi
  - type: PersistentVolumeClaim
    max:
      storage: 200Gi
    min:
      storage: 5Gi
