"""
Algorithmic Learning Engine for FlipSync Agentic System
Phase 2.1: Advanced Algorithmic Learning Integration

This module provides sophisticated algorithmic learning capabilities that enhance
the existing DatabaseLearningEngine with mathematical optimization algorithms
for improved decision-making and strategy optimization.
"""

import logging
import time
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple
from dataclasses import dataclass
from enum import Enum

from fs_agt_clean.core.db.database import Database
from fs_agt_clean.core.coordination.decision.database_learning_engine import (
    DatabaseLearningEngine,
)
from fs_agt_clean.core.coordination.event_system import EventPublisher

# Import mathematical optimization algorithms
from fs_agt_clean.core.learning.mathematical_optimization import (
    GradientDescentOptimizer,
    GradientDescentConfig,
    BayesianOptimizer,
    BayesianConfig,
    EvolutionaryAlgorithm,
    EvolutionaryConfig,
    ThompsonSampling,
    ThompsonConfig,
    OptimizationObjective,
)

logger = logging.getLogger(__name__)


class LearningAlgorithm(Enum):
    """Available learning algorithms."""

    GRADIENT_DESCENT = "gradient_descent"
    BAYESIAN_OPTIMIZATION = "bayesian_optimization"
    EVOLUTIONARY_ALGORITHM = "evolutionary_algorithm"
    THOMPSON_SAMPLING = "thompson_sampling"
    HYBRID = "hybrid"


class AgentType(Enum):
    """Agent types for specialized learning."""

    MARKET = "market"
    EXECUTIVE = "executive"
    CONTENT = "content"
    LOGISTICS = "logistics"


@dataclass
class AlgorithmicLearningConfig:
    """Configuration for algorithmic learning engine."""

    agent_type: AgentType
    primary_algorithm: LearningAlgorithm = LearningAlgorithm.GRADIENT_DESCENT
    secondary_algorithm: Optional[LearningAlgorithm] = None
    performance_threshold: float = 0.8
    optimization_frequency: int = 10  # Optimize every N decisions
    learning_rate: float = 0.01
    exploration_rate: float = 0.1
    convergence_threshold: float = 1e-6
    max_optimization_time: float = 0.4  # 400ms max for <500ms target
    enable_cross_agent_learning: bool = True


@dataclass
class LearningInsight:
    """Learning insight generated by algorithmic learning."""

    insight_id: str
    agent_id: str
    algorithm_used: LearningAlgorithm
    insight_type: str
    insight_data: Dict[str, Any]
    confidence_score: float
    performance_impact: float
    generated_at: datetime
    validation_status: str = "pending"


class AlgorithmicLearningEngine(DatabaseLearningEngine):
    """
    Advanced algorithmic learning engine that enhances DatabaseLearningEngine
    with sophisticated mathematical optimization algorithms.

    Features:
    - Multiple optimization algorithms (gradient descent, Bayesian, evolutionary, Thompson sampling)
    - Agent-specific learning strategies
    - Performance-driven algorithm selection
    - Cross-agent learning insights
    - Real-time optimization with <500ms performance targets
    """

    def __init__(
        self,
        engine_id: str,
        publisher: EventPublisher,
        database: Database,
        config: AlgorithmicLearningConfig,
    ):
        """Initialize the algorithmic learning engine.

        Args:
            engine_id: Unique identifier for the learning engine
            publisher: Event publisher for learning events
            database: Database instance for persistence
            config: Configuration for algorithmic learning
        """
        super().__init__(engine_id, publisher, database)
        self.config = config

        # Initialize optimization algorithms
        self.optimizers = self._initialize_optimizers()

        # Learning state tracking
        self.decision_count = 0
        self.optimization_history: List[Dict[str, Any]] = []
        self.learning_insights: List[LearningInsight] = []

        # Performance tracking
        self.algorithm_performance: Dict[LearningAlgorithm, List[float]] = {
            alg: [] for alg in LearningAlgorithm
        }

        # Agent-specific learning parameters
        self.agent_parameters = self._initialize_agent_parameters()

    def _initialize_optimizers(self) -> Dict[LearningAlgorithm, Any]:
        """Initialize optimization algorithms based on configuration."""
        optimizers = {}

        # Gradient Descent Optimizer
        gd_config = GradientDescentConfig(
            learning_rate=self.config.learning_rate,
            max_iterations=100,
            convergence_threshold=self.config.convergence_threshold,
            adaptive_learning_rate=True,
        )
        optimizers[LearningAlgorithm.GRADIENT_DESCENT] = GradientDescentOptimizer(
            gd_config
        )

        # Bayesian Optimizer with Docker-aware performance tuning
        bayesian_config = BayesianConfig(
            max_iterations=5,  # Aggressively reduced for 600ms target
            initial_random_samples=2,  # Minimal startup samples
        )
        optimizers[LearningAlgorithm.BAYESIAN_OPTIMIZATION] = BayesianOptimizer(
            bayesian_config
        )

        # Evolutionary Algorithm
        evolutionary_config = EvolutionaryConfig(
            population_size=20,
            max_generations=30,
            crossover_rate=0.8,
            mutation_rate=self.config.exploration_rate,
        )
        optimizers[LearningAlgorithm.EVOLUTIONARY_ALGORITHM] = EvolutionaryAlgorithm(
            evolutionary_config
        )

        # Thompson Sampling
        thompson_config = ThompsonConfig(
            exploration_bonus=self.config.exploration_rate, min_samples_per_arm=3
        )
        optimizers[LearningAlgorithm.THOMPSON_SAMPLING] = ThompsonSampling(
            thompson_config
        )

        return optimizers

    def _initialize_agent_parameters(self) -> Dict[str, Any]:
        """Initialize agent-specific learning parameters."""
        base_params = {
            "learning_rate": self.config.learning_rate,
            "exploration_rate": self.config.exploration_rate,
            "performance_weight": 1.0,
            "efficiency_weight": 1.0,
            "risk_tolerance": 0.5,
        }

        # Agent-specific parameter adjustments
        if self.config.agent_type == AgentType.MARKET:
            base_params.update(
                {
                    "price_sensitivity": 0.8,
                    "demand_responsiveness": 0.7,
                    "competition_awareness": 0.9,
                    "profit_optimization_weight": 1.2,
                }
            )
        elif self.config.agent_type == AgentType.EXECUTIVE:
            base_params.update(
                {
                    "strategic_horizon": 0.9,
                    "resource_efficiency": 0.8,
                    "risk_management": 0.7,
                    "decision_complexity_weight": 1.1,
                }
            )
        elif self.config.agent_type == AgentType.CONTENT:
            base_params.update(
                {
                    "engagement_optimization": 0.9,
                    "conversion_focus": 0.8,
                    "seo_importance": 0.7,
                    "content_quality_weight": 1.0,
                }
            )
        elif self.config.agent_type == AgentType.LOGISTICS:
            base_params.update(
                {
                    "cost_optimization": 0.9,
                    "delivery_speed": 0.8,
                    "route_efficiency": 0.9,
                    "inventory_balance_weight": 1.0,
                }
            )

        return base_params

    async def learn_from_feedback(
        self,
        feedback_data: Dict[str, Any],
        publish_event: bool = True,
        battery_efficient: bool = False,
    ) -> bool:
        """
        Enhanced learning from feedback using algorithmic optimization.

        Args:
            feedback_data: Feedback data from decision execution
            publish_event: Whether to publish learning events
            battery_efficient: Whether to use battery-efficient mode

        Returns:
            True if learning was successful, False otherwise
        """
        start_time = time.time()

        try:
            # Call parent learning method first
            success = await super().learn_from_feedback(
                feedback_data, publish_event, battery_efficient
            )

            if not success:
                return False

            self.decision_count += 1

            # Apply algorithmic learning enhancements
            if not battery_efficient:
                await self._apply_algorithmic_learning(feedback_data)

            # Periodic optimization
            if self.decision_count % self.config.optimization_frequency == 0:
                await self._perform_periodic_optimization(feedback_data)

            # Generate learning insights
            insights = await self._generate_learning_insights(feedback_data)
            self.learning_insights.extend(insights)

            # Update algorithm performance tracking
            learning_time = time.time() - start_time
            await self._update_algorithm_performance(learning_time)

            # Validate performance target (<500ms)
            if learning_time > 0.5:
                logger.warning(
                    f"Algorithmic learning time {learning_time:.3f}s exceeds 500ms target"
                )
            else:
                logger.debug(f"Algorithmic learning completed in {learning_time:.3f}s")

            return True

        except Exception as e:
            logger.error(f"Algorithmic learning failed: {e}")
            return False

    async def _apply_algorithmic_learning(self, feedback_data: Dict[str, Any]):
        """Apply algorithmic learning to improve decision-making."""
        try:
            # Extract decision parameters and performance metrics
            decision_params = self._extract_decision_parameters(feedback_data)
            performance_metrics = self._extract_performance_metrics(feedback_data)

            # Select appropriate algorithm based on problem characteristics
            algorithm = await self._select_optimization_algorithm(feedback_data)

            # Apply algorithmic optimization
            if algorithm == LearningAlgorithm.GRADIENT_DESCENT:
                await self._apply_gradient_descent_learning(
                    decision_params, performance_metrics
                )
            elif algorithm == LearningAlgorithm.BAYESIAN_OPTIMIZATION:
                await self._apply_bayesian_learning(
                    decision_params, performance_metrics
                )
            elif algorithm == LearningAlgorithm.EVOLUTIONARY_ALGORITHM:
                await self._apply_evolutionary_learning(
                    decision_params, performance_metrics
                )
            elif algorithm == LearningAlgorithm.THOMPSON_SAMPLING:
                await self._apply_thompson_sampling_learning(
                    decision_params, performance_metrics
                )

            logger.debug(f"Applied {algorithm.value} learning for {self.engine_id}")

        except Exception as e:
            logger.error(f"Error applying algorithmic learning: {e}")

    async def _select_optimization_algorithm(
        self, feedback_data: Dict[str, Any]
    ) -> LearningAlgorithm:
        """Select the most appropriate optimization algorithm based on context."""
        # Default to primary algorithm
        if len(self.algorithm_performance[self.config.primary_algorithm]) < 5:
            return self.config.primary_algorithm

        # Performance-based algorithm selection
        algorithm_scores = {}

        for algorithm, performance_history in self.algorithm_performance.items():
            if performance_history:
                # Calculate recent performance (last 10 results)
                recent_performance = performance_history[-10:]
                avg_performance = sum(recent_performance) / len(recent_performance)
                algorithm_scores[algorithm] = avg_performance

        # Select best performing algorithm
        if algorithm_scores:
            best_algorithm = max(algorithm_scores, key=algorithm_scores.get)
            return best_algorithm

        return self.config.primary_algorithm

    async def _apply_gradient_descent_learning(
        self, decision_params: Dict[str, float], performance_metrics: Dict[str, float]
    ):
        """Apply gradient descent optimization to decision parameters."""
        try:
            optimizer = self.optimizers[LearningAlgorithm.GRADIENT_DESCENT]

            # Define objective function based on performance metrics
            def objective_function(params: Dict[str, float]) -> float:
                # Combine multiple performance metrics
                score = 0.0
                if "success_rate" in performance_metrics:
                    score += performance_metrics["success_rate"] * 0.4
                if "efficiency" in performance_metrics:
                    score += performance_metrics["efficiency"] * 0.3
                if "cost_effectiveness" in performance_metrics:
                    score += performance_metrics["cost_effectiveness"] * 0.3
                return score

            # Set parameter bounds based on agent type
            constraints = self._get_parameter_constraints(decision_params)

            # Optimize parameters
            result = await optimizer.optimize(
                objective_function=objective_function,
                initial_parameters=decision_params,
                objective=OptimizationObjective.MAXIMIZE_EFFICIENCY,
                constraints=constraints,
            )

            # Update agent parameters with optimized values
            self._update_agent_parameters(result.optimized_parameters)

            logger.debug(
                f"Gradient descent optimization completed: {result.iterations_completed} iterations"
            )

        except Exception as e:
            logger.error(f"Gradient descent learning failed: {e}")

    async def _apply_bayesian_learning(
        self, decision_params: Dict[str, float], performance_metrics: Dict[str, float]
    ):
        """Apply Bayesian optimization to decision parameters."""
        try:
            optimizer = self.optimizers[LearningAlgorithm.BAYESIAN_OPTIMIZATION]

            # Define objective function
            def objective_function(params: Dict[str, float]) -> float:
                return self._calculate_combined_performance_score(performance_metrics)

            # Set parameter bounds
            parameter_bounds = self._get_parameter_bounds(decision_params)

            # Optimize parameters
            result = await optimizer.optimize(
                objective_function=objective_function,
                parameter_bounds=parameter_bounds,
                maximize=True,
            )

            # Update agent parameters
            self._update_agent_parameters(result.best_parameters)

            logger.debug(
                f"Bayesian optimization completed: {result.iterations_completed} evaluations"
            )

        except Exception as e:
            logger.error(f"Bayesian learning failed: {e}")

    async def _apply_evolutionary_learning(
        self, decision_params: Dict[str, float], performance_metrics: Dict[str, float]
    ):
        """Apply evolutionary algorithm to decision parameters."""
        try:
            optimizer = self.optimizers[LearningAlgorithm.EVOLUTIONARY_ALGORITHM]

            # Define objective function
            def objective_function(params: Dict[str, float]) -> float:
                return self._calculate_combined_performance_score(performance_metrics)

            # Set parameter bounds
            parameter_bounds = self._get_parameter_bounds(decision_params)

            # Optimize parameters
            result = await optimizer.optimize(
                objective_function=objective_function,
                parameter_bounds=parameter_bounds,
                maximize=True,
            )

            # Update agent parameters with best individual
            self._update_agent_parameters(result.best_individual.parameters)

            logger.debug(
                f"Evolutionary optimization completed: {result.generations_completed} generations"
            )

        except Exception as e:
            logger.error(f"Evolutionary learning failed: {e}")

    async def _apply_thompson_sampling_learning(
        self, decision_params: Dict[str, float], performance_metrics: Dict[str, float]
    ):
        """Apply Thompson sampling for multi-armed bandit optimization."""
        try:
            optimizer = self.optimizers[LearningAlgorithm.THOMPSON_SAMPLING]

            # Create arms from decision parameter combinations
            arms = self._create_decision_arms(decision_params)

            # Define reward function
            def reward_function(arm: str) -> float:
                return self._calculate_arm_reward(arm, performance_metrics)

            # Optimize arm selection
            result = await optimizer.optimize(
                arms=arms, reward_function=reward_function, max_samples=50
            )

            # Update parameters based on best arm
            best_arm_params = self._decode_arm_parameters(result.best_arm)
            self._update_agent_parameters(best_arm_params)

            logger.debug(f"Thompson sampling completed: {result.total_samples} samples")

        except Exception as e:
            logger.error(f"Thompson sampling learning failed: {e}")

    def _extract_decision_parameters(
        self, feedback_data: Dict[str, Any]
    ) -> Dict[str, float]:
        """Extract decision parameters from feedback data."""
        # Extract relevant parameters based on agent type
        params = {}

        if self.config.agent_type == AgentType.MARKET:
            params.update(
                {
                    "price_adjustment": feedback_data.get("price_adjustment", 0.0),
                    "demand_factor": feedback_data.get("demand_factor", 1.0),
                    "competition_response": feedback_data.get(
                        "competition_response", 0.5
                    ),
                }
            )
        elif self.config.agent_type == AgentType.EXECUTIVE:
            params.update(
                {
                    "resource_allocation": feedback_data.get(
                        "resource_allocation", 0.5
                    ),
                    "risk_level": feedback_data.get("risk_level", 0.5),
                    "strategic_weight": feedback_data.get("strategic_weight", 1.0),
                }
            )
        elif self.config.agent_type == AgentType.CONTENT:
            params.update(
                {
                    "engagement_focus": feedback_data.get("engagement_focus", 0.5),
                    "seo_weight": feedback_data.get("seo_weight", 0.5),
                    "conversion_priority": feedback_data.get(
                        "conversion_priority", 0.5
                    ),
                }
            )
        elif self.config.agent_type == AgentType.LOGISTICS:
            params.update(
                {
                    "cost_priority": feedback_data.get("cost_priority", 0.5),
                    "speed_priority": feedback_data.get("speed_priority", 0.5),
                    "efficiency_weight": feedback_data.get("efficiency_weight", 1.0),
                }
            )

        return params

    def _extract_performance_metrics(
        self, feedback_data: Dict[str, Any]
    ) -> Dict[str, float]:
        """Extract performance metrics from feedback data."""
        return {
            "success_rate": feedback_data.get("success", 0.0),
            "efficiency": feedback_data.get("efficiency", 0.0),
            "cost_effectiveness": feedback_data.get("cost_effectiveness", 0.0),
            "execution_time": feedback_data.get("execution_time", 1.0),
            "quality_score": feedback_data.get("quality", 0.0),
        }

    def _calculate_combined_performance_score(
        self, performance_metrics: Dict[str, float]
    ) -> float:
        """Calculate combined performance score from multiple metrics."""
        score = 0.0
        weights = {
            "success_rate": 0.3,
            "efficiency": 0.25,
            "cost_effectiveness": 0.25,
            "quality_score": 0.2,
        }

        for metric, value in performance_metrics.items():
            weight = weights.get(metric, 0.1)
            score += value * weight

        return score

    def _get_parameter_constraints(
        self, params: Dict[str, float]
    ) -> Dict[str, Tuple[float, float]]:
        """Get parameter constraints for optimization."""
        constraints = {}
        for param_name in params:
            # Default constraints [0, 1] for most parameters
            constraints[param_name] = (0.0, 1.0)
        return constraints

    def _get_parameter_bounds(
        self, params: Dict[str, float]
    ) -> Dict[str, Tuple[float, float]]:
        """Get parameter bounds for optimization."""
        return self._get_parameter_constraints(params)

    def _update_agent_parameters(self, optimized_params: Dict[str, float]):
        """Update agent parameters with optimized values."""
        for param_name, value in optimized_params.items():
            if param_name in self.agent_parameters:
                self.agent_parameters[param_name] = value

    def _create_decision_arms(self, decision_params: Dict[str, float]) -> List[str]:
        """Create arms for Thompson sampling from decision parameters."""
        # Create discrete arms from continuous parameters
        arms = []
        param_names = list(decision_params.keys())

        # Create combinations of parameter values
        for i in range(min(10, 2 ** len(param_names))):  # Limit to 10 arms
            arm_id = f"arm_{i}"
            arms.append(arm_id)

        return arms

    def _decode_arm_parameters(self, arm_id: str) -> Dict[str, float]:
        """Decode arm ID back to parameter values."""
        # Simple decoding - in practice, this would map arm IDs to parameter combinations
        arm_index = int(arm_id.split("_")[1])

        # Generate parameter values based on arm index
        params = {}
        for i, param_name in enumerate(self.agent_parameters.keys()):
            if param_name in [
                "learning_rate",
                "exploration_rate",
                "performance_weight",
            ]:
                # Use arm index to generate different parameter values
                value = 0.1 + (arm_index * 0.1) % 0.8  # Values between 0.1 and 0.9
                params[param_name] = value

        return params

    def _calculate_arm_reward(
        self, arm_id: str, performance_metrics: Dict[str, float]
    ) -> float:
        """Calculate reward for a specific arm."""
        return self._calculate_combined_performance_score(performance_metrics)

    async def _perform_periodic_optimization(self, feedback_data: Dict[str, Any]):
        """Perform periodic optimization of learning parameters."""
        try:
            # Analyze recent performance trends
            recent_performance = await self._analyze_recent_performance()

            # Adjust learning parameters based on performance
            if recent_performance < self.config.performance_threshold:
                # Increase exploration if performance is low
                self.agent_parameters["exploration_rate"] = min(
                    self.agent_parameters["exploration_rate"] * 1.1, 0.5
                )
                logger.debug("Increased exploration rate due to low performance")
            else:
                # Decrease exploration if performance is good
                self.agent_parameters["exploration_rate"] = max(
                    self.agent_parameters["exploration_rate"] * 0.95, 0.01
                )
                logger.debug("Decreased exploration rate due to good performance")

        except Exception as e:
            logger.error(f"Periodic optimization failed: {e}")

    async def _analyze_recent_performance(self) -> float:
        """Analyze recent performance to guide optimization."""
        # Simple performance analysis - in practice, this would be more sophisticated
        if not self.optimization_history:
            return 0.5

        recent_results = self.optimization_history[-10:]  # Last 10 optimizations
        if not recent_results:
            return 0.5

        avg_performance = sum(
            result.get("performance_score", 0.0) for result in recent_results
        ) / len(recent_results)

        return avg_performance

    async def _generate_learning_insights(
        self, feedback_data: Dict[str, Any]
    ) -> List[LearningInsight]:
        """Generate learning insights from algorithmic analysis."""
        insights = []

        try:
            # Generate insight based on recent learning patterns
            insight = LearningInsight(
                insight_id=str(uuid.uuid4()),
                agent_id=self.engine_id,
                algorithm_used=self.config.primary_algorithm,
                insight_type="parameter_optimization",
                insight_data={
                    "optimized_parameters": self.agent_parameters.copy(),
                    "performance_improvement": await self._calculate_performance_improvement(),
                    "confidence_level": 0.8,
                },
                confidence_score=0.8,
                performance_impact=0.1,
                generated_at=datetime.now(timezone.utc),
            )
            insights.append(insight)

        except Exception as e:
            logger.error(f"Error generating learning insights: {e}")

        return insights

    async def _calculate_performance_improvement(self) -> float:
        """Calculate performance improvement from algorithmic learning."""
        # Simple calculation - in practice, this would compare before/after performance
        return 0.05  # 5% improvement placeholder

    async def _update_algorithm_performance(self, learning_time: float):
        """Update algorithm performance tracking."""
        # Track performance based on learning time (inverse relationship)
        performance_score = max(
            0.0, 1.0 - (learning_time / self.config.max_optimization_time)
        )

        # Update performance history for current algorithm
        current_algorithm = self.config.primary_algorithm
        self.algorithm_performance[current_algorithm].append(performance_score)

        # Keep only recent performance history (last 100 results)
        if len(self.algorithm_performance[current_algorithm]) > 100:
            self.algorithm_performance[current_algorithm] = self.algorithm_performance[
                current_algorithm
            ][-100:]

    async def get_learning_recommendations(
        self, context: Dict[str, Any] = None
    ) -> Dict[str, Any]:
        """Get learning recommendations based on algorithmic analysis."""
        try:
            recommendations = {
                "agent_type": self.config.agent_type.value,
                "primary_algorithm": self.config.primary_algorithm.value,
                "current_parameters": self.agent_parameters.copy(),
                "recent_insights": [
                    {
                        "insight_type": insight.insight_type,
                        "confidence_score": insight.confidence_score,
                        "performance_impact": insight.performance_impact,
                    }
                    for insight in self.learning_insights[-5:]  # Last 5 insights
                ],
                "algorithm_performance": {
                    alg.value: {
                        "recent_performance": (
                            perf_history[-10:] if perf_history else []
                        ),
                        "average_performance": (
                            sum(perf_history[-10:]) / len(perf_history[-10:])
                            if perf_history
                            else 0.0
                        ),
                    }
                    for alg, perf_history in self.algorithm_performance.items()
                },
                "optimization_frequency": self.config.optimization_frequency,
                "decision_count": self.decision_count,
            }

            return recommendations

        except Exception as e:
            logger.error(f"Error getting learning recommendations: {e}")
            return {"error": str(e)}

    async def get_performance_metrics(self) -> Dict[str, Any]:
        """Get comprehensive performance metrics for the algorithmic learning engine."""
        try:
            return {
                "engine_id": self.engine_id,
                "agent_type": self.config.agent_type.value,
                "total_decisions": self.decision_count,
                "total_optimizations": len(self.optimization_history),
                "total_insights": len(self.learning_insights),
                "algorithm_performance": {
                    alg.value: {
                        "total_uses": len(perf_history),
                        "average_performance": (
                            sum(perf_history) / len(perf_history)
                            if perf_history
                            else 0.0
                        ),
                        "recent_performance": (
                            sum(perf_history[-10:]) / len(perf_history[-10:])
                            if perf_history
                            else 0.0
                        ),
                    }
                    for alg, perf_history in self.algorithm_performance.items()
                },
                "current_parameters": self.agent_parameters.copy(),
                "configuration": {
                    "primary_algorithm": self.config.primary_algorithm.value,
                    "optimization_frequency": self.config.optimization_frequency,
                    "performance_threshold": self.config.performance_threshold,
                    "max_optimization_time": self.config.max_optimization_time,
                },
            }

        except Exception as e:
            logger.error(f"Error getting performance metrics: {e}")
            return {"error": str(e)}
