apiVersion: v1
kind: Namespace
metadata:
  name: flipsync-dev
  labels:
    environment: development
    app: flipsync
    tier: agent-system
  annotations:
    flipsync.io/security-monitoring: "enabled"
    flipsync.io/agent-coordination: "enabled"
